### ISSUE TITLE
Mark Tarver's SEQUEL system 7.0 and 5.3

### ISSUE THREAD

**Issue by bitmappergit** [theoremprover-museum/theoremprover-museum.github.io#23]
https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/lisp/code/tools/sequel/
turns out they were here all along

**Comment by kohlhase** [comment]
That is very nice, I would make add information according to the schema to https://github.com/theoremprover-museum/theoremprover-museum.github.io/blob/master/_data/provers.yml?
See the [documentation](https://github.com/theoremprover-museum/theoremprover-museum.github.io/blob/master/_data/)
for IMPS this is :

```
- name: IMPS
  authors: William M. Farmer, Joshua D. Guttman, F. Javier Thayer
  active: false
  status: museum
  teaser: The IMPS Theorem Prover.
  TPMarchive: imps
  language: Scheme, Common Lisp 
  swmath: 9143
```

**Comment by tkw1536** [comment]
Looking at the sources, it looks like it should be the following:

```
- name: SEQUEL
  active: false
  teaser:  For generating type-secure and efficient Lisp programs.
  homepage: https://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/lisp/code/tools/sequel/0.html
  authors: Mark Tarver
  repos: https://github.com/theoremprover-museum/SEQUEL
  development: 1990-1994
  language: Common Lisp
```

I've also mirrored the website linked above to https://github.com/theoremprover-museum/SEQUEL.

**Comment by kohlhase** [comment]
I have added that to the museum.
