### ISSUE TITLE
move to a Jekyll-based setup (easier to have news, ... )?

### ISSUE THREAD

**Issue by kohlhase** [theoremprover-museum/theoremprover-museum.github.io#7]
We should think about this. It seems to me that we only have to copy over the setup from ICMS or so.

**Comment by tkw1536** [comment]
I have made this a very basic Jekyll site for now.

**Comment by kohlhase** [comment]
thanks, I will have a look and extend.

**Comment by kohlhase** [comment]
this looks great. but I would like to have news as well. I have written a couple of posts under `_posts` @tkw1536 could you integrate them?

**Comment by kohlhase** [comment]
also having an atom feed would be great.

**Comment by kohlhase** [comment]
the setup  can be copied from the openmath or KWARC sites.

**Comment by kohlhase** [comment]
All in all, this looks much much better.

**Comment by kohlhase** [comment]
OH, and we need the timestamp for the swMATH.

**Comment by tkw1536** [comment]
Added news, timestamp, and proper urls. 

Closing this issue, as the initial move is completed. Please create separate issues for other improvements.

**Comment by kohlhase** [comment]
thanks a lot.
